// generated by stringer -type=State; DO NOT EDIT

package upower

import "fmt"

const _State_name = "UnknownChargingDischargingEmptyFullChargedPendingChargePendingDischarge"

var _State_index = [...]uint8{0, 7, 15, 26, 31, 42, 55, 71}

func (i State) String() string {
	if i < 0 || i+1 >= State(len(_State_index)) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
